<a href="https://colab.research.google.com/github/GauraoM/PyTorch/blob/main/Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import torch

#### Training Data

In [4]:
# Input(Temperature, rainfall, humidity)
inputs = np.array([[73,67,43],
                   [91,88,64],
                   [87,134,58],
                   [102,43,37],
                   [69,96,70]], dtype = 'float32')

In [5]:
# Targets(apples, oranges)
targets = np.array([[56,70],
                    [81,101],
                    [119,133],
                    [22,37],
                    [103,119]], dtype='float32')

In [6]:
# Convert input and target to tensor
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [8]:
# weights and biases
w = torch.randn(2,3, requires_grad = True)
b = torch.randn(2, requires_grad = True)
print(w)
print(b)

tensor([[-1.8424,  2.0182,  1.6328],
        [ 1.3150, -0.1094, -0.5694]], requires_grad=True)
tensor([ 0.5747, -0.3161], requires_grad=True)


In [9]:
def model(x):
  return x@w.t()+b

In [10]:
# Generate Predictions
preds = model(inputs)
print(preds)

tensor([[ 71.5056,  63.8703],
        [115.0127,  73.2874],
        [205.4212,  66.4124],
        [-40.1582, 108.0471],
        [181.4887,  40.0658]], grad_fn=<AddBackward0>)


In [11]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [12]:
# MSE Loss
def mse(t1,t2):
  diff = t1- t2
  return torch.sum(diff*diff)/ diff.numel()  

In [13]:
# Compute the loss
loss = mse(preds, targets)
loss

tensor(3540.7793, grad_fn=<DivBackward0>)

In [14]:
# Compute gradients
loss.backward()

In [15]:
# Gradients for weights
print(w)
print(w.grad)

tensor([[-1.8424,  2.0182,  1.6328],
        [ 1.3150, -0.1094, -0.5694]], requires_grad=True)
tensor([[ 2164.2593,  4094.9094,  2210.0681],
        [-1392.4189, -3258.9597, -1759.1835]])


In [17]:
print(b)
print(b.grad)

tensor([ 0.5747, -0.3161], requires_grad=True)
tensor([ 30.4540, -21.6634])


In [19]:
# Reset values to zero
w.grad.zero_()
b.grad.zero_()

tensor([0., 0.])

#### Train the model using Gradient descent

In [20]:
# Generate Predictions
preds = model(inputs)
preds

tensor([[ 71.5056,  63.8703],
        [115.0127,  73.2874],
        [205.4212,  66.4124],
        [-40.1582, 108.0471],
        [181.4887,  40.0658]], grad_fn=<AddBackward0>)

In [21]:
# Compute the loss
loss = mse(preds, targets)
loss

tensor(3540.7793, grad_fn=<DivBackward0>)

In [22]:
# Compute gradients
loss.backward()
print(w.grad)
print(b.grad)

tensor([[ 2164.2593,  4094.9094,  2210.0681],
        [-1392.4189, -3258.9597, -1759.1835]])
tensor([ 30.4540, -21.6634])


In [23]:
# Adjust the weights and reset gradient
# Disable grad with torch.no_grad
with torch.no_grad():
  w -= w.grad * 1e-5
  b -= b.grad * 1e-5
  w.grad.zero_()
  b.grad.zero_()

In [24]:
print(w)
print(b)

tensor([[-1.8641,  1.9772,  1.6107],
        [ 1.3289, -0.0768, -0.5518]], requires_grad=True)
tensor([ 0.5744, -0.3159], requires_grad=True)


In [25]:
# Now we have new weights and biases we can calculate the loss
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(3155.8823, grad_fn=<DivBackward0>)


#### Training for multiple inputs

In [31]:
# Train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [33]:
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(260.9915, grad_fn=<DivBackward0>)


In [34]:
preds

tensor([[ 52.5346,  75.3997],
        [ 83.1612,  96.1959],
        [123.9690, 134.9495],
        [ -5.9834,  66.1178],
        [119.4887,  94.3076]], grad_fn=<AddBackward0>)

In [35]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

### Linear regression by PyTorch Built in

In [1]:
import torch.nn as nn

In [4]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [5]:
print(inputs)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])


#### Dataset and DataLoader
a TensorDataset, which allows access to rows from inputs and targets as tuples, and provides standard APIs for working with many different types of datasets in PyTorch.

In [6]:
from torch.utils.data import TensorDataset

#####The `TensorDataset` allows us to access a small section of the training data using the array indexing notation (`[0:3]` in the above code). It returns a tuple with two elements. The first element contains the input variables for the selected rows, and the second contains the targets.

In [7]:
train_ds = TensorDataset(inputs, targets)
train_ds[:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

#### We will also create a DataLoader, which can split the data into batches of a predefined size while training. It also provides other utilities like shuffling and random sampling of the data.

In [8]:
from torch.utils.data import DataLoader

In [10]:
batch_size = 5
train_dl = DataLoader(train_ds,batch_size, shuffle=True)

#### nn.Linear

In [11]:
model = nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.1930, -0.1349, -0.3186],
        [ 0.5747, -0.2177, -0.1297]], requires_grad=True)
Parameter containing:
tensor([-0.4162, -0.1517], requires_grad=True)


In [13]:
# Generate predictions

preds = model(inputs)
preds

tensor([[-37.2400,  21.6405],
        [-50.2362,  24.6897],
        [-53.7587,  13.1554],
        [-37.6871,  44.3112],
        [-48.9813,   9.5252],
        [-37.2980,  22.4329],
        [-50.4198,  24.7776],
        [-54.2702,  13.6004],
        [-37.6291,  43.5188],
        [-49.1068,   8.8207],
        [-37.4236,  21.7284],
        [-50.2942,  25.4821],
        [-53.5751,  13.0675],
        [-37.5616,  45.0157],
        [-48.9232,   8.7328]], grad_fn=<AddmmBackward0>)

#### Loss Function
In-built mse loss

In [16]:
import torch.nn.functional as F

In [17]:
loss_fn = F.mse_loss

In [19]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(11677.7559, grad_fn=<MseLossBackward0>)


#### Optimizers

In [20]:
opt = torch.optim.SGD(model.parameters(), lr = 1e-5)

#### Train the model

In [24]:
# utility function to trai the model
def fit(num_epochs, model, loss_fn, train_dl):

  # Iterate over epochs
  for epoch in range(num_epochs):

    # Train with batches of data
    for xb, yb in train_dl:

      # Generate prediction
      pred = model(xb)

      # calculate loss
      loss = loss_fn(pred, yb)

      # Compute gradient
      loss.backward()

      # update parameters
      opt.step()

      # Reset gradient to zero
      opt.zero_grad()

    # Print the progress
    if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [25]:
fit(100, model, loss_fn, train_dl)

Epoch [10/100], Loss: 735.9875
Epoch [20/100], Loss: 1060.4053
Epoch [30/100], Loss: 206.3429
Epoch [40/100], Loss: 328.6606
Epoch [50/100], Loss: 260.1038
Epoch [60/100], Loss: 114.3652
Epoch [70/100], Loss: 170.1622
Epoch [80/100], Loss: 126.8944
Epoch [90/100], Loss: 79.7785
Epoch [100/100], Loss: 27.6769


In [26]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 58.2143,  72.3782],
        [ 79.7123,  98.0354],
        [121.5642, 135.6409],
        [ 28.1425,  48.7710],
        [ 93.4593, 107.6625],
        [ 57.0748,  71.4927],
        [ 79.0623,  97.5458],
        [121.6300, 135.9951],
        [ 29.2820,  49.6565],
        [ 93.9488, 108.0585],
        [ 57.5643,  71.8887],
        [ 78.5729,  97.1499],
        [122.2142, 136.1305],
        [ 27.6530,  48.3750],
        [ 94.5988, 108.5480]], grad_fn=<AddmmBackward0>)

In [27]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])