<a href="https://colab.research.google.com/github/GauraoM/PyTorch/blob/main/PyTorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
# Vector
t2 = torch.tensor([1.,2,3,4,5])
t2

tensor([1., 2., 3., 4., 5.])

In [3]:
# Matrix
t3 = torch.tensor([[1.,2],[3,4],[5,6],[7.,8]])
t3

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])

In [4]:
# 3D array
t4 = torch.tensor([
                   [[1,2],
                    [3,4]],
                   [[5,6],
                    [7,8]]
])
t4

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

#### Tensor Operations and Gradient

In [5]:
# Create tensors.
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [8]:
y = w*x + b
y.backward()
print(y)

tensor(17., grad_fn=<AddBackward0>)


In [9]:
# Display gradients
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(6.)
dy/db: tensor(2.)


#### Inter operability between torch and numpy 

In [12]:
import numpy as np

x =np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
y = torch.from_numpy(x) # Doesn't craete a copy
y

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
x.dtype, y.dtype

(dtype('int64'), torch.int64)

In [15]:
# Convert tensor to numpy array
z = y.numpy()
z

array([[1, 2, 3],
       [4, 5, 6]])